apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nyk37w8av-java-quarkus
  janus-idp.io/tekton: nyk37w8av-java-quarkus
  backstage.io/kubernetes-id: nyk37w8av-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nyk37w8av-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
